import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative smooth-scroll">
          <div className=" bg-background"></div>
          {/* <div className="fixed inset-0 bg-gradient-to-r from-[#e7d954] via-[#222222] via-30% to-[#041f04]"></div> */}
          {/* <div className="fixed inset-0 bg-gradient-to-r from-[#f4e45558] via-[#222222] via-30% to-[#222222]"></div> */}
          {/* <div className="fixed inset-0 bg-gradient-to-br from-[#29622a55] via-[#12282cf5] via-15% to-[#295a62f5]"></div> */}

          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
